local:
  sqlserver:
    server: ".\\SQL19"
    dbname: "GoDB"
    user: "sa"
    password: "1"
  api:
    port: ":7071"
    appkeys: ["HeaderAppKey1","HeaderAppKey2"]
  jwt:
    secret: "blablablafalanfilanintermilan**_?4406"
